# Generated by Django 4.1.2 on 2022-10-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_parent_alter_profile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('view_student', 'Can view Student Page'),)},
        ),
    ]
